/************************************************************
 * HMMER - Biological sequence analysis with profile HMMs
 * Copyright (C) 1992-2006 HHMI Janelia Farm
 * All Rights Reserved
 *
 *     This source code is distributed under the terms of the
 *     GNU General Public License. See the files COPYING and LICENSE
 *     for details.
 ************************************************************/

/* masks.c
 *
 * Sequence masking routines; corrections for biased composition
 * target sequences.
 *
 * The Claverie/States XNU code is not used by default because I
 * consider X'ing out sequence to be too black/white and too
 * aggressive, but it's available as an option.
 *
 * The Wooton/Federhen SEG code was studied, but deemed too
 * nonportable to include; it would've suffered the same drawback
 * as XNU.
 *
 * The TraceScoreCorrection() code is the default.
 */


#include <stdio.h>
#include <math.h>
#include <float.h>

#include "structs.hpp"
#include "vectorops.hpp"



/* Function: XNU()
 * Purpose:  x-out of repetitive sequence. XNU tends to be
 *           good at x'ing out short period tandem repeats.
 *
 * Note:     Apply /only/ to protein sequence.
 *
 * Args:     dsq: 1..len digitized sequence
 *           len: length of dsq
 *
 * Return:   number of characters x'ed out.
 */
int
XNU(
  unsigned char *dsq,
  int len);


/* Function: TraceScoreCorrection()
 * Purpose:  Calculate a correction (in integer log_2 odds) to be
 *           applied to a sequence, using a second null model,
 *           based on a traceback. M/I emissions are corrected;
 *           C/N/J are not -- as if the nonmatching part and
 *           matching part were each generated by the best null model.
 *           The null model is constructed /post hoc/ as the
 *           average over all the M,I distributions used by the trace.
 *
 * Return:   the log_2-odds score correction.
 */
float
TraceScoreCorrection(
  struct plan7_s *hmm,
  struct p7trace_s *tr,
  unsigned char *dsq);
